name: playnet

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */20 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    - main
    - output
    
  

jobs:
  generate:
    runs-on: ubuntu-latest
    
    
    steps:
     - name: Screenshot
       uses: lowlighter/metrics@latest
       with:
         filename: metrics.plugin.playnet.screenshot.svg
         token: NOT_NEEDED
         base: ""
         plugin_pagespeed: yes
         plugin_pagespeed_screenshot: yes
         plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
         plugin_pagespeed_url: https://playnet-sandy.vercel.app/
